name: twilio_flutter
description: A Package that helps with twilio API.Currenty supports only sms sending functionality.With time more features will be released.
version: 0.0.6
homepage: https://github.com/adarshbalu/twilio_flutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.1
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
